# Generated by Django 6.0 on 2025-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch_later', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='name_movie',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name_user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='data_add',
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
