# Generated by Django 6.0 on 2025-12-13 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch_later', '0002_rename_name_movie_name_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='to_watch_later.movie'),
            preserve_default=False,
        ),
    ]
