# Generated by Django 6.0 on 2025-12-13 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch_later', '0003_movie_date_add_user_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movies',
        ),
        migrations.CreateModel(
            name='ListMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_watch_later.movie')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_watch_later.user')),
            ],
        ),
    ]
