# Generated by Django 6.0 on 2025-12-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch_later', '0004_remove_user_movies_listmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_add',
        ),
    ]
