# Generated by Django 6.0 on 2025-12-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch_later', '0005_remove_movie_date_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmovies',
            options={'verbose_name_plural': 'Movies List'},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
